import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile } from 'node:fs/promises';

import * as esbuild from 'esbuild';

const watch = process.argv.includes('--watch');

function git(args) {
  // A build without git available is still a usable build; it just can't say
  // which commit it came from.
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function buildStamp() {
  const now = new Date();
  const pad = (value) => String(value).padStart(2, '0');
  const when =
    `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ` +
    `${pad(now.getHours())}:${pad(now.getMinutes())}`;

  const commit = git(['rev-parse', '--short', 'HEAD']) || 'unknown';

  return `${when} ${commit}`;
}

const { version } = JSON.parse(await readFile('package.json', 'utf8'));

const shared = {
  bundle: true,
  sourcemap: true,
  logLevel: 'info',
  define: {
    __BUILD_STAMP__: JSON.stringify(buildStamp()),
    __APP_VERSION__: JSON.stringify(version),
  },
};

const targets = [
  {
    ...shared,
    entryPoints: ['src/hosts/electron/electron-main.ts'],
    outfile: 'dist/main.js',
    platform: 'node',
    format: 'esm',
    // electron-updater resolves parts of itself at runtime, so it ships as a
    // real dependency rather than being bundled in.
    external: ['electron', 'electron-updater'],
  },
  {
    // Preload stays CommonJS: an ESM preload would need the sandbox turned off.
    ...shared,
    entryPoints: ['src/hosts/electron/preload-bridge.ts'],
    outfile: 'dist/preload.cjs',
    platform: 'node',
    format: 'cjs',
    external: ['electron'],
  },
  {
    // What he installs. Built from the renderer's own entry, which cannot reach
    // src/mockup — so the pretend store is not in the app at all.
    ...shared,
    entryPoints: ['src/hosts/electron/browser-entry.ts'],
    outfile: 'dist/renderer.js',
    platform: 'browser',
    format: 'iife',
  },
  {
    // The same interface for a plain browser, with the mock behind it. Separate
    // output folder so the two can never be confused for one another.
    ...shared,
    entryPoints: ['src/hosts/mockup/browser-entry.ts'],
    outfile: 'dist-browser/renderer.js',
    platform: 'browser',
    format: 'iife',
  },
];

await mkdir('dist', { recursive: true });
await mkdir('dist-browser', { recursive: true });
await cp('src/ui/index.html', 'dist/index.html');
await cp('src/ui/index.html', 'dist-browser/index.html');

/*
  The mark, to both. The SVG is what the page asks for as its favicon, which is
  the only icon the browser build has and the one visible while the interface is
  being worked on.

  The PNG is for the window in a dev run: what he installs takes its icon from
  the exe, but `electron .` here would otherwise wear Electron's own. Both are
  generated by `scripts/make-icon.mjs` and committed, so a build never depends
  on a browser being installed to draw them.
*/
await cp('assets/icon.svg', 'dist/icon.svg');
await cp('assets/icon.svg', 'dist-browser/icon.svg');
await cp('build/icon.png', 'dist/icon.png');

if (watch) {
  const contexts = await Promise.all(targets.map((options) => esbuild.context(options)));
  await Promise.all(contexts.map((context) => context.watch()));
  console.log('watching for changes');
} else {
  await Promise.all(targets.map((options) => esbuild.build(options)));
}
